services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mathly
      POSTGRES_PASSWORD: mathly
      POSTGRES_DB: mathly
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_dev_data:
