import { Aldrich } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { getUserInfo } from "@/components/auth/getUserInfo";

import Snow from "@/components/layout/snow";

const aldrich = Aldrich({
  variable: "--font-aldrich",
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Math concepts",
  description: "Generated by create next app", 
};

export default async function RootLayout({ children }) {

    const user = await getUserInfo();

  return (
    <html lang="en">
      <body
        className={`${aldrich.className} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <Navbar/>
          <Snow/>
          {children}
        </AuthProvider>

      </body>
    </html>
  );
}
