import { Aldrich } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";

const aldrich = Aldrich({
  variable: "--font-aldrich",
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Math concepts",
  description: "Generated by create next app", 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${aldrich.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
